import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Chatbox from "@/components/chatbox/Chatbot";

export const metadata: Metadata = {
  title: "EZPhone",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo/ezphone_logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Chatbox />
      </body>
    </html>
  );
}
