
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Chatbox from "@/components/chatbox/Chatbot";
import AppProviders from "./providers";
import CartDrawerOverlay from "@/components/common/CartDrawerOverlay";
import GlobalRouteGuard from "@/lib/guards/GlobalRouteGuard";
import Footer from "@/components/footer/Footer";


export const metadata: Metadata = {
  title: "EZBuy",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo/ezbuy_logo_favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        <AppProviders>
          {/* <GlobalRouteGuard /> */}
          <Navbar />
          {children}
          <Chatbox />
          <CartDrawerOverlay />
          <Footer />
        </AppProviders>
      </body>
    </html>
  );
}
